# Hermes Dispatch Tool — AI Agent Red Team Cost Calculator
# Source: https://hermesdispatch.dev/tools/agent-redteam-cost-calculator/
# Description: Estimate cost to red-team an AI agent based on scope, provider, and severity mix.
# License: MIT (generated by hermesdispatch.dev)
#
# INSTALL:
#   1. Save this file as ~/.hermes/hermes-agent/tools/agent_redteam_cost_calculator.py
#   2. Restart Hermes or run /reset in a session
#   3. The tool auto-registers if Hermes uses auto-discovery of tools/*.py
#
# MANUAL REGISTRY (if auto-discovery is off):
#   from tools.agent_redteam_cost_calculator import register
#   register()

import json

DATA = {}

def _ok(result):
    return json.dumps({"success": True, "data": result}, indent=2)

def _err(message):
    return json.dumps({"success": False, "error": message}, indent=2)


TOOL_NAME = "agent_redteam_cost_calculator"
TOOLSET = "agents"

SCHEMA = {
  "type": "function",
  "function": {
    "name": "agent_redteam_cost_calculator",
    "description": "Estimate cost to red-team an AI agent based on scope, provider, and severity mix.",
    "parameters": {
      "type": "object",
      "properties": {
        "provider_daily_rate": {
          "type": "number",
          "description": "Daily rate for red-team provider in USD."
        },
        "days": {
          "type": "integer",
          "description": "Number of red-team days."
        },
        "tests_per_day": {
          "type": "integer",
          "description": "Average tests run per day."
        },
        "remediation_hours": {
          "type": "number",
          "description": "Hours of remediation per high-severity finding."
        }
      },
      "required": []
    }
  }
}

def _run(args):
    rate = float(args.get("provider_daily_rate", 4000))
    days = int(args.get("days", 5))
    tests = int(args.get("tests_per_day", 20))
    rem_hours = float(args.get("remediation_hours", 8))
    engagement_cost = rate * days
    total_tests = tests * days
    estimated_high = max(1, int(total_tests * 0.15))
    remediation_cost = estimated_high * rem_hours * 150
    total = engagement_cost + remediation_cost
    return _ok({
        "engagement_cost": round(engagement_cost, 2),
        "remediation_cost": round(remediation_cost, 2),
        "total_estimated_cost": round(total, 2),
        "total_tests": total_tests,
        "estimated_high_severity_findings": estimated_high
    })

def HANDLER(args):
    try:
        return _run(args)
    except Exception as e:
        return _err(str(e))


def register():
    """Manual registry hook. Import and call this to register with Hermes."""
    try:
        from tools.registry import registry
        registry.register(
            name=TOOL_NAME,
            toolset=TOOLSET,
            schema=SCHEMA,
            handler=HANDLER,
        )
    except ImportError:
        print("Hermes registry not found; skipping manual registration.")

if __name__ == "__main__":
    # CLI smoke test
    print(HANDLER({}))
