# Hermes Dispatch Tool — Agent Prompt Injection Scanner
# Source: https://hermesdispatch.dev/tools/agent-prompt-injection-scanner/
# Description: Score an AI agent prompt or system message for prompt-injection exposure.
# License: MIT (generated by hermesdispatch.dev)
#
# INSTALL:
#   1. Save this file as ~/.hermes/hermes-agent/tools/agent_prompt_injection_scanner.py
#   2. Restart Hermes or run /reset in a session
#   3. The tool auto-registers if Hermes uses auto-discovery of tools/*.py
#
# MANUAL REGISTRY (if auto-discovery is off):
#   from tools.agent_prompt_injection_scanner import register
#   register()

import json

DATA = {}

def _ok(result):
    return json.dumps({"success": True, "data": result}, indent=2)

def _err(message):
    return json.dumps({"success": False, "error": message}, indent=2)


TOOL_NAME = "agent_prompt_injection_scanner"
TOOLSET = "agents"

SCHEMA = {
  "type": "function",
  "function": {
    "name": "agent_prompt_injection_scanner",
    "description": "Score an AI agent prompt or system message for prompt-injection exposure.",
    "parameters": {
      "type": "object",
      "properties": {
        "system_prompt": {
          "type": "string",
          "description": "System prompt or agent instructions to scan."
        },
        "user_input": {
          "type": "string",
          "description": "Sample user input that reaches the agent."
        }
      },
      "required": [
        "system_prompt"
      ]
    }
  }
}

def _run(args):
    prompt = (args.get("system_prompt", "") or "").lower()
    user = (args.get("user_input", "") or "").lower()
    combined = prompt + " " + user
    checks = {
        "ignore_previous": "ignore" in combined or "previous instructions" in combined,
        "role_switching": "you are now" in combined or "act as" in combined,
        "delimiter_manipulation": "###" in combined or "<|" in combined or "</system" in combined,
        "instruction_override": "do not" in combined and "instead" in combined,
        "output_format_abuse": "print" in combined and ("password" in combined or "secret" in combined or "token" in combined),
    }
    score = sum(1 for v in checks.values() if v)
    risk = "low" if score == 0 else ("medium" if score <= 2 else "high")
    return _ok({
        "risk_level": risk,
        "score": score,
        "checks": checks,
        "recommendation": "Add input/output filtering, privilege separation, and human-in-the-loop for high-risk paths."
    })

def HANDLER(args):
    try:
        return _run(args)
    except Exception as e:
        return _err(str(e))


def register():
    """Manual registry hook. Import and call this to register with Hermes."""
    try:
        from tools.registry import registry
        registry.register(
            name=TOOL_NAME,
            toolset=TOOLSET,
            schema=SCHEMA,
            handler=HANDLER,
        )
    except ImportError:
        print("Hermes registry not found; skipping manual registration.")

if __name__ == "__main__":
    # CLI smoke test
    print(HANDLER({}))
