# Hermes Dispatch Tool — AI Agent SLA / Uptime Calculator
# Source: https://hermesdispatch.dev/tools/agent-sla-calculator/
# Description: Convert uptime percentage to allowed downtime and estimate revenue at risk.
# License: MIT (generated by hermesdispatch.dev)
#
# INSTALL:
#   1. Save this file as ~/.hermes/hermes-agent/tools/agent_sla_calculator.py
#   2. Restart Hermes or run /reset in a session
#   3. The tool auto-registers if Hermes uses auto-discovery of tools/*.py
#
# MANUAL REGISTRY (if auto-discovery is off):
#   from tools.agent_sla_calculator import register
#   register()

import json

DATA = {}

def _ok(result):
    return json.dumps({"success": True, "data": result}, indent=2)

def _err(message):
    return json.dumps({"success": False, "error": message}, indent=2)


TOOL_NAME = "agent_sla_calculator"
TOOLSET = "agents"

SCHEMA = {
  "type": "function",
  "function": {
    "name": "agent_sla_calculator",
    "description": "Convert uptime percentage to allowed downtime and estimate revenue at risk.",
    "parameters": {
      "type": "object",
      "properties": {
        "uptime_pct": {
          "type": "number",
          "description": "Target uptime percentage (e.g. 99.9)."
        },
        "monthly_revenue": {
          "type": "number",
          "description": "Monthly revenue dependent on the agent."
        }
      },
      "required": [
        "uptime_pct"
      ]
    }
  }
}

def _run(args):
    uptime = float(args.get("uptime_pct", 99.9))
    revenue = float(args.get("monthly_revenue", 0))
    minutes_per_month = 30 * 24 * 60
    allowed_downtime_min = minutes_per_month * (1 - uptime / 100)
    allowed_downtime_hr = allowed_downtime_min / 60
    revenue_at_risk = revenue * (1 - uptime / 100)
    return _ok({
        "uptime_pct": uptime,
        "allowed_downtime_minutes_month": round(allowed_downtime_min, 1),
        "allowed_downtime_hours_month": round(allowed_downtime_hr, 2),
        "allowed_downtime_hours_year": round(allowed_downtime_hr * 12, 1),
        "revenue_at_risk_monthly": round(revenue_at_risk, 2),
        "revenue_at_risk_yearly": round(revenue_at_risk * 12, 2)
    })

def HANDLER(args):
    try:
        return _run(args)
    except Exception as e:
        return _err(str(e))


def register():
    """Manual registry hook. Import and call this to register with Hermes."""
    try:
        from tools.registry import registry
        registry.register(
            name=TOOL_NAME,
            toolset=TOOLSET,
            schema=SCHEMA,
            handler=HANDLER,
        )
    except ImportError:
        print("Hermes registry not found; skipping manual registration.")

if __name__ == "__main__":
    # CLI smoke test
    print(HANDLER({}))
