# Hermes Dispatch Tool — AI Agent Latency Budget Calculator
# Source: https://hermesdispatch.dev/tools/agent-latency-budget-calculator/
# Description: Estimate end-to-end AI agent response latency across providers, architectures, retrieval, and tool calls.
# License: MIT (generated by hermesdispatch.dev)
#
# INSTALL:
#   1. Save this file as ~/.hermes/hermes-agent/tools/agent_latency_budget_calculator.py
#   2. Restart Hermes or run /reset in a session
#   3. The tool auto-registers if Hermes uses auto-discovery of tools/*.py
#
# MANUAL REGISTRY (if auto-discovery is off):
#   from tools.agent_latency_budget_calculator import register
#   register()

import json

DATA = {}

def _ok(result):
    return json.dumps({"success": True, "data": result}, indent=2)

def _err(message):
    return json.dumps({"success": False, "error": message}, indent=2)


TOOL_NAME = "agent_latency_budget_calculator"
TOOLSET = "agents"

SCHEMA = {
  "type": "function",
  "function": {
    "name": "agent_latency_budget_calculator",
    "description": "Estimate end-to-end AI agent response latency across providers, architectures, retrieval, and tool calls.",
    "parameters": {
      "type": "object",
      "properties": {
        "ttft_ms": {
          "type": "number",
          "description": "Time to first token in milliseconds."
        },
        "tbt_ms": {
          "type": "number",
          "description": "Time between tokens in milliseconds."
        },
        "output_tokens": {
          "type": "integer",
          "description": "Expected output tokens."
        },
        "retrieval_ms": {
          "type": "number",
          "description": "Retrieval step latency in milliseconds."
        },
        "tool_calls": {
          "type": "integer",
          "description": "Number of tool call round trips."
        },
        "tool_latency_ms": {
          "type": "number",
          "description": "Tool execution latency in milliseconds."
        },
        "network_rtt_ms": {
          "type": "number",
          "description": "Network round-trip time in milliseconds."
        }
      },
      "required": [
        "ttft_ms",
        "tbt_ms",
        "output_tokens"
      ]
    }
  }
}

def _run(args):
    ttft = float(args.get("ttft_ms", 0))
    tbt = float(args.get("tbt_ms", 0))
    output_tokens = int(args.get("output_tokens", 0))
    retrieval = float(args.get("retrieval_ms", 0))
    tool_calls = int(args.get("tool_calls", 0))
    tool_latency = float(args.get("tool_latency_ms", 0))
    rtt = float(args.get("network_rtt_ms", 50))
    generation_time = tbt * output_tokens
    tool_time = tool_calls * (tool_latency + 2 * rtt)
    total_ms = ttft + retrieval + generation_time + tool_time + rtt
    return _ok({
        "total_latency_ms": round(total_ms, 1),
        "generation_time_ms": round(generation_time, 1),
        "retrieval_time_ms": round(retrieval, 1),
        "tool_time_ms": round(tool_time, 1),
        "network_rtt_ms": round(rtt, 1),
        "note": "P50 target is typical; add 20-50% for P95."
    })

def HANDLER(args):
    try:
        return _run(args)
    except Exception as e:
        return _err(str(e))


def register():
    """Manual registry hook. Import and call this to register with Hermes."""
    try:
        from tools.registry import registry
        registry.register(
            name=TOOL_NAME,
            toolset=TOOLSET,
            schema=SCHEMA,
            handler=HANDLER,
        )
    except ImportError:
        print("Hermes registry not found; skipping manual registration.")

if __name__ == "__main__":
    # CLI smoke test
    print(HANDLER({}))
