# Hermes Dispatch Tool — AI Startup Cost Calculator
# Source: https://hermesdispatch.dev/tools/ai-startup-cost-calculator/
# Description: Estimate first-year AI startup costs across compute, models, tools, and team.
# License: MIT (generated by hermesdispatch.dev)
#
# INSTALL:
#   1. Save this file as ~/.hermes/hermes-agent/tools/ai_startup_cost_calculator.py
#   2. Restart Hermes or run /reset in a session
#   3. The tool auto-registers if Hermes uses auto-discovery of tools/*.py
#
# MANUAL REGISTRY (if auto-discovery is off):
#   from tools.ai_startup_cost_calculator import register
#   register()

import json

DATA = {}

def _ok(result):
    return json.dumps({"success": True, "data": result}, indent=2)

def _err(message):
    return json.dumps({"success": False, "error": message}, indent=2)


TOOL_NAME = "ai_startup_cost_calculator"
TOOLSET = "agents"

SCHEMA = {
  "type": "function",
  "function": {
    "name": "ai_startup_cost_calculator",
    "description": "Estimate first-year AI startup costs across compute, models, tools, and team.",
    "parameters": {
      "type": "object",
      "properties": {
        "team_size": {
          "type": "integer",
          "description": "Initial team size."
        },
        "avg_salary": {
          "type": "number",
          "description": "Average annual salary per person in USD."
        },
        "cloud_compute_monthly": {
          "type": "number",
          "description": "Monthly cloud compute spend in USD."
        },
        "api_spend_monthly": {
          "type": "number",
          "description": "Monthly LLM/API spend in USD."
        },
        "tools_monthly": {
          "type": "number",
          "description": "Monthly SaaS/tool spend in USD."
        },
        "months": {
          "type": "integer",
          "description": "Number of months to model."
        }
      },
      "required": []
    }
  }
}

def _run(args):
    team = int(args.get("team_size", 1))
    salary = float(args.get("avg_salary", 120000))
    compute = float(args.get("cloud_compute_monthly", 500))
    api = float(args.get("api_spend_monthly", 1000))
    tools = float(args.get("tools_monthly", 300))
    months = int(args.get("months", 12))
    people_cost = team * salary * (months / 12)
    infra_cost = (compute + api + tools) * months
    total = people_cost + infra_cost
    return _ok({
        "people_cost": round(people_cost, 2),
        "infrastructure_cost": round(infra_cost, 2),
        "total_first_year_cost": round(total, 2),
        "monthly_burn": round(total / months, 2)
    })

def HANDLER(args):
    try:
        return _run(args)
    except Exception as e:
        return _err(str(e))


def register():
    """Manual registry hook. Import and call this to register with Hermes."""
    try:
        from tools.registry import registry
        registry.register(
            name=TOOL_NAME,
            toolset=TOOLSET,
            schema=SCHEMA,
            handler=HANDLER,
        )
    except ImportError:
        print("Hermes registry not found; skipping manual registration.")

if __name__ == "__main__":
    # CLI smoke test
    print(HANDLER({}))
