# Hermes Dispatch Tool — AI Voice Agent Cost Calculator
# Source: https://hermesdispatch.dev/tools/ai-voice-agent-cost-calculator/
# Description: Estimate monthly cost for an AI voice agent by minutes, provider, and concurrency.
# License: MIT (generated by hermesdispatch.dev)
#
# INSTALL:
#   1. Save this file as ~/.hermes/hermes-agent/tools/ai_voice_agent_cost_calculator.py
#   2. Restart Hermes or run /reset in a session
#   3. The tool auto-registers if Hermes uses auto-discovery of tools/*.py
#
# MANUAL REGISTRY (if auto-discovery is off):
#   from tools.ai_voice_agent_cost_calculator import register
#   register()

import json

DATA = {}

def _ok(result):
    return json.dumps({"success": True, "data": result}, indent=2)

def _err(message):
    return json.dumps({"success": False, "error": message}, indent=2)


TOOL_NAME = "ai_voice_agent_cost_calculator"
TOOLSET = "agents"

SCHEMA = {
  "type": "function",
  "function": {
    "name": "ai_voice_agent_cost_calculator",
    "description": "Estimate monthly cost for an AI voice agent by minutes, provider, and concurrency.",
    "parameters": {
      "type": "object",
      "properties": {
        "minutes_per_month": {
          "type": "integer",
          "description": "Total voice minutes per month."
        },
        "cost_per_minute": {
          "type": "number",
          "description": "Cost per minute in USD."
        },
        "concurrent_calls": {
          "type": "integer",
          "description": "Average concurrent calls."
        },
        "llm_cost_per_minute": {
          "type": "number",
          "description": "LLM/transport cost per minute in USD."
        }
      },
      "required": [
        "minutes_per_month"
      ]
    }
  }
}

def _run(args):
    minutes = int(args.get("minutes_per_month", 0))
    voice_rate = float(args.get("cost_per_minute", 0.05))
    llm_rate = float(args.get("llm_cost_per_minute", 0.03))
    voice_cost = minutes * voice_rate
    llm_cost = minutes * llm_rate
    total = voice_cost + llm_cost
    return _ok({
        "voice_cost": round(voice_cost, 2),
        "llm_transport_cost": round(llm_cost, 2),
        "total_monthly_cost": round(total, 2),
        "cost_per_hour": round(total / max(minutes / 60, 1), 2)
    })

def HANDLER(args):
    try:
        return _run(args)
    except Exception as e:
        return _err(str(e))


def register():
    """Manual registry hook. Import and call this to register with Hermes."""
    try:
        from tools.registry import registry
        registry.register(
            name=TOOL_NAME,
            toolset=TOOLSET,
            schema=SCHEMA,
            handler=HANDLER,
        )
    except ImportError:
        print("Hermes registry not found; skipping manual registration.")

if __name__ == "__main__":
    # CLI smoke test
    print(HANDLER({}))
