# Hermes Dispatch Tool — LLM Cost Calculator
# Source: https://hermesdispatch.dev/tools/llm-cost-calculator/
# Description: Compare cloud API token prices vs local GPU cost per 1M tokens.
# License: MIT (generated by hermesdispatch.dev)
#
# INSTALL:
#   1. Save this file as ~/.hermes/hermes-agent/tools/llm_cost_calculator.py
#   2. Restart Hermes or run /reset in a session
#
# MANUAL REGISTRY:
#   from tools.llm_cost_calculator import register
#   register()

import json

def _ok(result):
    return json.dumps({"success": True, "data": result}, indent=2)

def _err(message):
    return json.dumps({"success": False, "error": message}, indent=2)


TOOL_NAME = "llm_cost_calculator"
TOOLSET = "cost"

SCHEMA = {
    "type": "function",
    "function": {
        "name": TOOL_NAME,
        "description": "Compare monthly cloud LLM API cost vs local GPU inference cost.",
        "parameters": {
            "type": "object",
            "properties": {
                "input_tokens_per_call": {"type": "integer", "default": 1000, "description": "Average input tokens per API call."},
                "output_tokens_per_call": {"type": "integer", "default": 500, "description": "Average output tokens per API call."},
                "calls_per_month": {"type": "integer", "default": 10000, "description": "Number of calls per month."},
                "provider": {"type": "string", "default": "openai", "description": "Cloud provider: openai, anthropic, google, groq, together."},
                "local_gpu_cost": {"type": "number", "default": 2000, "description": "Upfront local GPU cost in USD."},
                "gpu_lifespan_months": {"type": "integer", "default": 36, "description": "Expected GPU lifespan in months."},
            },
            "required": []
        }
    }
}

# Approximate per-1M-token pricing in USD (input, output)
PRICING = {
    "openai": {"input": 0.150, "output": 0.600, "name": "OpenAI GPT-4o-mini"},
    "anthropic": {"input": 0.800, "output": 2.400, "name": "Anthropic Claude 3 Haiku"},
    "google": {"input": 0.350, "output": 1.400, "name": "Google Gemini 1.5 Flash"},
    "groq": {"input": 0.050, "output": 0.080, "name": "Groq Llama 3 8B"},
    "together": {"input": 0.200, "output": 0.200, "name": "Together AI Llama 3 8B"},
}

def calculate_cost(input_tokens_per_call=1000, output_tokens_per_call=500, calls_per_month=10000,
                   provider="openai", local_gpu_cost=2000, gpu_lifespan_months=36):
    rates = PRICING.get(provider.lower(), PRICING["openai"])
    monthly_input_tokens = input_tokens_per_call * calls_per_month
    monthly_output_tokens = output_tokens_per_call * calls_per_month
    cloud_cost = (monthly_input_tokens / 1_000_000) * rates["input"] + (monthly_output_tokens / 1_000_000) * rates["output"]
    local_amortized = local_gpu_cost / gpu_lifespan_months
    break_even_months = local_gpu_cost / cloud_cost if cloud_cost > 0 else float('inf')
    cheaper = "local GPU" if local_amortized < cloud_cost else "cloud API"
    return _ok({
        "cloud_cost_per_month": round(cloud_cost, 2),
        "local_gpu_cost_per_month": round(local_amortized, 2),
        "break_even_months": round(break_even_months, 1) if break_even_months != float('inf') else None,
        "cheaper_option": cheaper,
        "provider": rates["name"],
    })

def HANDLER(args):
    try:
        return calculate_cost(
            input_tokens_per_call=int(args.get("input_tokens_per_call", 1000)),
            output_tokens_per_call=int(args.get("output_tokens_per_call", 500)),
            calls_per_month=int(args.get("calls_per_month", 10000)),
            provider=args.get("provider", "openai"),
            local_gpu_cost=float(args.get("local_gpu_cost", 2000)),
            gpu_lifespan_months=int(args.get("gpu_lifespan_months", 36)),
        )
    except Exception as e:
        return _err(str(e))


def register():
    try:
        from tools.registry import registry
        registry.register(name=TOOL_NAME, toolset=TOOLSET, schema=SCHEMA, handler=HANDLER)
    except ImportError:
        print("Hermes registry not found; skipping manual registration.")

if __name__ == "__main__":
    print(HANDLER({{}}))
