# Hermes Dispatch Tool — LLM Fine-Tuning Cost Calculator
# Source: https://hermesdispatch.dev/tools/llm-fine-tuning-cost-calculator/
# Description: Estimate cost to fine-tune a model by tokens, epochs, and compute option.
# License: MIT (generated by hermesdispatch.dev)
#
# INSTALL:
#   1. Save this file as ~/.hermes/hermes-agent/tools/llm_fine_tuning_cost_calculator.py
#   2. Restart Hermes or run /reset in a session
#   3. The tool auto-registers if Hermes uses auto-discovery of tools/*.py
#
# MANUAL REGISTRY (if auto-discovery is off):
#   from tools.llm_fine_tuning_cost_calculator import register
#   register()

import json

DATA = {}

def _ok(result):
    return json.dumps({"success": True, "data": result}, indent=2)

def _err(message):
    return json.dumps({"success": False, "error": message}, indent=2)


TOOL_NAME = "llm_fine_tuning_cost_calculator"
TOOLSET = "ai"

SCHEMA = {
  "type": "function",
  "function": {
    "name": "llm_fine_tuning_cost_calculator",
    "description": "Estimate cost to fine-tune a model by tokens, epochs, and compute option.",
    "parameters": {
      "type": "object",
      "properties": {
        "tokens": {
          "type": "integer",
          "description": "Number of training tokens."
        },
        "epochs": {
          "type": "integer",
          "description": "Training epochs."
        },
        "price_per_1m_tokens": {
          "type": "number",
          "description": "Provider price per 1M tokens trained."
        },
        "gpu_hours": {
          "type": "number",
          "description": "Local GPU hours if self-hosting."
        },
        "gpu_hourly_cost": {
          "type": "number",
          "description": "Local/cloud GPU cost per hour."
        }
      },
      "required": [
        "tokens"
      ]
    }
  }
}

def _run(args):
    tokens = int(args.get("tokens", 0))
    epochs = int(args.get("epochs", 3))
    price = float(args.get("price_per_1m_tokens", 5.0))
    gpu_hours = float(args.get("gpu_hours", 0))
    gpu_rate = float(args.get("gpu_hourly_cost", 2.0))
    provider_cost = (tokens * epochs / 1e6) * price
    self_host_cost = gpu_hours * gpu_rate
    return _ok({
        "provider_cost": round(provider_cost, 2),
        "self_host_cost": round(self_host_cost, 2),
        "cheaper_option": "provider" if provider_cost <= self_host_cost else "self-host",
        "total_token_passes": tokens * epochs
    })

def HANDLER(args):
    try:
        return _run(args)
    except Exception as e:
        return _err(str(e))


def register():
    """Manual registry hook. Import and call this to register with Hermes."""
    try:
        from tools.registry import registry
        registry.register(
            name=TOOL_NAME,
            toolset=TOOLSET,
            schema=SCHEMA,
            handler=HANDLER,
        )
    except ImportError:
        print("Hermes registry not found; skipping manual registration.")

if __name__ == "__main__":
    # CLI smoke test
    print(HANDLER({}))
