# Hermes Dispatch Tool — Local LLM ROI Calculator
# Source: https://hermesdispatch.dev/tools/local-llm-roi-calculator/
# Description: Compare 3-year TCO of local GPU inference versus cloud API.
# License: MIT (generated by hermesdispatch.dev)
#
# INSTALL:
#   1. Save this file as ~/.hermes/hermes-agent/tools/local_llm_roi_calculator.py
#   2. Restart Hermes or run /reset in a session
#
# MANUAL REGISTRY:
#   from tools.local_llm_roi_calculator import register
#   register()

import json

def _ok(result):
    return json.dumps({"success": True, "data": result}, indent=2)

def _err(message):
    return json.dumps({"success": False, "error": message}, indent=2)


TOOL_NAME = "local_llm_roi_calculator"
TOOLSET = "cost"

SCHEMA = {
    "type": "function",
    "function": {
        "name": TOOL_NAME,
        "description": "Compare 3-year total cost of ownership for local GPU inference vs cloud API.",
        "parameters": {
            "type": "object",
            "properties": {
                "gpu_cost": {"type": "number", "default": 2000, "description": "GPU + system upfront cost in USD."},
                "power_w": {"type": "number", "default": 350, "description": "Average power draw in watts."},
                "electricity_rate": {"type": "number", "default": 0.12, "description": "Electricity cost per kWh."},
                "utilization_pct": {"type": "number", "default": 40, "description": "Average GPU utilization percentage."},
                "cloud_cost_per_month": {"type": "number", "default": 300, "description": "Current monthly cloud API spend in USD."},
                "projection_months": {"type": "integer", "default": 36, "description": "Months to project."},
            },
            "required": []
        }
    }
}

def roi_calculator(gpu_cost=2000, power_w=350, electricity_rate=0.12, utilization_pct=40,
                   cloud_cost_per_month=300, projection_months=36):
    hours_per_day = 24 * (utilization_pct / 100)
    electricity_monthly = (power_w / 1000) * hours_per_day * 30 * electricity_rate
    local_total = gpu_cost + (electricity_monthly * projection_months)
    cloud_total = cloud_cost_per_month * projection_months
    savings = cloud_total - local_total
    break_even = gpu_cost / (cloud_cost_per_month - electricity_monthly) if cloud_cost_per_month > electricity_monthly else float('inf')
    return _ok({
        "local_total_3yr": round(local_total, 2),
        "cloud_total_3yr": round(cloud_total, 2),
        "savings_3yr": round(savings, 2),
        "break_even_months": round(break_even, 1) if break_even != float('inf') else None,
        "recommendation": "Buy local GPU" if savings > 0 else "Stick with cloud API",
    })

def HANDLER(args):
    try:
        return roi_calculator(
            gpu_cost=float(args.get("gpu_cost", 2000)),
            power_w=float(args.get("power_w", 350)),
            electricity_rate=float(args.get("electricity_rate", 0.12)),
            utilization_pct=float(args.get("utilization_pct", 40)),
            cloud_cost_per_month=float(args.get("cloud_cost_per_month", 300)),
            projection_months=int(args.get("projection_months", 36)),
        )
    except Exception as e:
        return _err(str(e))


def register():
    try:
        from tools.registry import registry
        registry.register(name=TOOL_NAME, toolset=TOOLSET, schema=SCHEMA, handler=HANDLER)
    except ImportError:
        print("Hermes registry not found; skipping manual registration.")

if __name__ == "__main__":
    print(HANDLER({{}}))
