# Hermes Dispatch Tool — Miner Pivot Calculator
# Source: https://hermesdispatch.dev/tools/miner-pivot-calculator/
# Description: Compare crypto mining profit vs local LLM inference revenue vs selling a GPU.
# License: MIT (generated by hermesdispatch.dev)
#
# INSTALL:
#   1. Save this file as ~/.hermes/hermes-agent/tools/miner_pivot_calculator.py
#   2. Restart Hermes or run /reset in a session
#
# MANUAL REGISTRY:
#   from tools.miner_pivot_calculator import register
#   register()

import json
import math

def _ok(result):
    return json.dumps({"success": True, "data": result}, indent=2)

def _err(message):
    return json.dumps({"success": False, "error": message}, indent=2)


TOOL_NAME = "miner_pivot_calculator"
TOOLSET = "crypto"

SCHEMA = {
    "type": "function",
    "function": {
        "name": TOOL_NAME,
        "description": "Compare crypto mining profit vs local LLM inference revenue vs selling a GPU for a given month.",
        "parameters": {
            "type": "object",
            "properties": {
                "hashrate_mh": {"type": "number", "description": "GPU hashrate in MH/s."},
                "power_w": {"type": "number", "description": "GPU power draw in watts."},
                "electricity_cost_per_kwh": {"type": "number", "default": 0.12, "description": "Electricity cost per kWh."},
                "mining_revenue_per_mh_day": {"type": "number", "default": 0.0008, "description": "Mining revenue per MH/s per day in USD."},
                "inference_8b_tok_s": {"type": "number", "description": "8B model inference speed in tokens/second."},
                "vram_gb": {"type": "number", "description": "GPU VRAM in GB."},
                "inference_price_per_1m_tokens": {"type": "number", "default": 0.10, "description": "Revenue per 1M output tokens in USD."},
                "utilization_pct": {"type": "number", "default": 40, "description": "GPU utilization for inference as a percentage (0-100)."},
                "market_price": {"type": "number", "default": 0, "description": "Current used market price of the GPU in USD (for sell estimate)."},
            },
            "required": ["hashrate_mh", "power_w", "inference_8b_tok_s", "vram_gb"]
        }
    }
}

def pivot_calculator(hashrate_mh, power_w, electricity_cost_per_kwh, mining_revenue_per_mh_day,
                     inference_8b_tok_s, vram_gb, inference_price_per_1m_tokens, utilization_pct, market_price):
    days = 30
    mining_revenue = hashrate_mh * mining_revenue_per_mh_day * days
    mining_power_cost = (power_w / 1000) * 24 * days * electricity_cost_per_kwh
    mining_profit = mining_revenue - mining_power_cost

    tokens_per_day = inference_8b_tok_s * 3600 * 24
    inference_revenue = tokens_per_day * days * (utilization_pct / 100) * (inference_price_per_1m_tokens / 1_000_000)

    sell_pct = 0.55 if vram_gb >= 16 else 0.35
    sell_estimate = market_price * sell_pct

    if mining_profit <= 0 and inference_revenue <= 0:
        verdict = "Sell the card"
        verdict_class = "red"
    elif inference_revenue > mining_profit * 1.2:
        verdict = "Pivot to AI inference"
        verdict_class = "emerald"
    elif mining_profit > inference_revenue * 1.2:
        verdict = "Keep mining"
        verdict_class = "amber"
    else:
        verdict = "Close call — test inference demand"
        verdict_class = "gold"

    return _ok({
        "verdict": verdict,
        "verdict_class": verdict_class,
        "mining_profit_per_month": round(mining_profit, 2),
        "inference_revenue_per_month": round(inference_revenue, 2),
        "sell_estimate": round(sell_estimate, 2),
        "mining_revenue_per_month": round(mining_revenue, 2),
        "mining_power_cost_per_month": round(mining_power_cost, 2),
    })

def HANDLER(args):
    try:
        return pivot_calculator(
            hashrate_mh=float(args.get("hashrate_mh")),
            power_w=float(args.get("power_w")),
            electricity_cost_per_kwh=float(args.get("electricity_cost_per_kwh", 0.12)),
            mining_revenue_per_mh_day=float(args.get("mining_revenue_per_mh_day", 0.0008)),
            inference_8b_tok_s=float(args.get("inference_8b_tok_s")),
            vram_gb=float(args.get("vram_gb")),
            inference_price_per_1m_tokens=float(args.get("inference_price_per_1m_tokens", 0.10)),
            utilization_pct=float(args.get("utilization_pct", 40)),
            market_price=float(args.get("market_price", 0)),
        )
    except Exception as e:
        return _err(str(e))


def register():
    """Manual registry hook."""
    try:
        from tools.registry import registry
        registry.register(name=TOOL_NAME, toolset=TOOLSET, schema=SCHEMA, handler=HANDLER)
    except ImportError:
        print("Hermes registry not found; skipping manual registration.")

if __name__ == "__main__":
    print(HANDLER({{}}))
