# Hermes Dispatch Tool — Miner Pivot Calculator
# Source: https://hermesdispatch.dev/tools/miner-pivot-calculator/
# Description: Compare crypto mining profit vs local LLM inference revenue for a GPU.
# License: MIT (generated by hermesdispatch.dev)
#
# INSTALL:
#   1. Save this file as ~/.hermes/hermes-agent/tools/miner_pivot_calculator_data.py
#   2. Restart Hermes or run /reset in a session
#
# MANUAL REGISTRY:
#   from tools.miner_pivot_calculator_data import register
#   register()

import json

DATA = json.loads(r'''{
  "gpus": {
    "nvidia-geforce-rtx-5090": {
      "name": "NVIDIA GeForce RTX 5090",
      "vram_gb": 32,
      "hashrate_mh": 150,
      "power_w": 575,
      "inference_8b_tok_s": 82,
      "msrp": 1999,
      "market_price": 2200
    },
    "nvidia-geforce-rtx-4090": {
      "name": "NVIDIA GeForce RTX 4090",
      "vram_gb": 24,
      "hashrate_mh": 130,
      "power_w": 450,
      "inference_8b_tok_s": 64,
      "msrp": 1599,
      "market_price": 1700
    },
    "nvidia-geforce-rtx-3090": {
      "name": "NVIDIA GeForce RTX 3090",
      "vram_gb": 24,
      "hashrate_mh": 120,
      "power_w": 350,
      "inference_8b_tok_s": 48,
      "msrp": 1499,
      "market_price": 800
    },
    "nvidia-geforce-rtx-4080-super": {
      "name": "NVIDIA GeForce RTX 4080 Super",
      "vram_gb": 16,
      "hashrate_mh": 95,
      "power_w": 320,
      "inference_8b_tok_s": 52,
      "msrp": 999,
      "market_price": 1000
    },
    "nvidia-geforce-rtx-4070-ti-super": {
      "name": "NVIDIA GeForce RTX 4070 Ti Super",
      "vram_gb": 16,
      "hashrate_mh": 80,
      "power_w": 285,
      "inference_8b_tok_s": 40,
      "msrp": 799,
      "market_price": 800
    }
  },
  "defaults": {
    "mining_revenue_per_mh_day": 0.006,
    "inference_price_per_1m_tokens": 0.1,
    "utilization_pct": 0.4,
    "electricity_cost_per_kwh": 0.12
  }
}''')

def _ok(result):
    return json.dumps({"success": True, "data": result}, indent=2)

def _err(message):
    return json.dumps({"success": False, "error": message}, indent=2)

TOOL_NAME = "miner_pivot_calculator_data"
TOOLSET = "crypto"

SCHEMA = {
  "type": "function",
  "function": {
    "name": "miner_pivot_calculator_data",
    "description": "Compare crypto mining profit vs local LLM inference revenue for a GPU.",
    "parameters": {
      "type": "object",
      "properties": {
        "gpu_slug": {
          "type": "string",
          "description": "Gpu Slug to look up."
        }
      },
      "required": [
        "gpu_slug"
      ]
    }
  }
}

def lookup(args):
    gpu_slug = args.get('gpu_slug', '').lower().strip()
    gpus = DATA.get('gpus', {})
    gpu = None
    for slug, info in gpus.items():
        if slug.lower() == gpu_slug or info.get('name', '').lower() == gpu_slug:
            gpu = dict(info); gpu['slug'] = slug; break
    if not gpu:
        return _err(f'GPU not found: {gpu_slug}. Available: ' + ', '.join(gpus.keys()))
    return _ok({'gpu': gpu})

def HANDLER(args):
    try:
        return lookup(args)
    except Exception as e:
        return _err(str(e))

def register():
    try:
        from tools.registry import registry
        registry.register(name=TOOL_NAME, toolset=TOOLSET, schema=SCHEMA, handler=HANDLER)
    except ImportError:
        print("Hermes registry not found; skipping manual registration.")

if __name__ == "__main__":
    print(HANDLER({}))
