# Hermes Dispatch Tool — Prompt Tokenizer & Pricing Estimator
# Source: https://hermesdispatch.dev/tools/prompt-tokenizer-pricing-estimator/
# Description: Estimate token count and API cost for a prompt using approximate word-to-token ratios.
# License: MIT (generated by hermesdispatch.dev)
#
# INSTALL:
#   1. Save this file as ~/.hermes/hermes-agent/tools/prompt_tokenizer_pricing_estimator.py
#   2. Restart Hermes or run /reset in a session
#   3. The tool auto-registers if Hermes uses auto-discovery of tools/*.py
#
# MANUAL REGISTRY (if auto-discovery is off):
#   from tools.prompt_tokenizer_pricing_estimator import register
#   register()

import json

DATA = {}

def _ok(result):
    return json.dumps({"success": True, "data": result}, indent=2)

def _err(message):
    return json.dumps({"success": False, "error": message}, indent=2)


TOOL_NAME = "prompt_tokenizer_pricing_estimator"
TOOLSET = "ai"

SCHEMA = {
  "type": "function",
  "function": {
    "name": "prompt_tokenizer_pricing_estimator",
    "description": "Estimate token count and API cost for a prompt using approximate word-to-token ratios.",
    "parameters": {
      "type": "object",
      "properties": {
        "prompt": {
          "type": "string",
          "description": "Prompt text to estimate."
        },
        "input_price_per_m": {
          "type": "number",
          "description": "Input price per 1M tokens."
        },
        "output_price_per_m": {
          "type": "number",
          "description": "Output price per 1M tokens."
        },
        "expected_output_words": {
          "type": "integer",
          "description": "Expected output word count."
        }
      },
      "required": [
        "prompt"
      ]
    }
  }
}

def _run(args):
    prompt = args.get("prompt", "")
    input_tok = len(prompt.split()) * 1.3
    output_tok = int(args.get("expected_output_words", 150)) * 1.3
    in_price = float(args.get("input_price_per_m", 0.5))
    out_price = float(args.get("output_price_per_m", 1.5))
    input_cost = (input_tok / 1e6) * in_price
    output_cost = (output_tok / 1e6) * out_price
    return _ok({
        "estimated_input_tokens": round(input_tok, 0),
        "estimated_output_tokens": round(output_tok, 0),
        "input_cost_usd": round(input_cost, 5),
        "output_cost_usd": round(output_cost, 5),
        "total_cost_usd": round(input_cost + output_cost, 5),
        "note": "Uses a rough 1.3 tokens/word estimate. Use tiktoken for exact counts."
    })

def HANDLER(args):
    try:
        return _run(args)
    except Exception as e:
        return _err(str(e))


def register():
    """Manual registry hook. Import and call this to register with Hermes."""
    try:
        from tools.registry import registry
        registry.register(
            name=TOOL_NAME,
            toolset=TOOLSET,
            schema=SCHEMA,
            handler=HANDLER,
        )
    except ImportError:
        print("Hermes registry not found; skipping manual registration.")

if __name__ == "__main__":
    # CLI smoke test
    print(HANDLER({}))
